public class MyDriver {
  public static void main(String[] args) {
  System.out.println("Real Numbers");
  RealNumber zero = new RealNumber(0);
  RealNumber first = new RealNumber(.5);
  RealNumber second = new RealNumber(1);
  RealNumber third = new RealNumber(-1 * first.getValue());
  System.out.println(zero + "(0)");
  System.out.println(first + "(.5)");
  System.out.println(second + "(1)");
  System.out.println(third + "(-.5)");
  System.out.println(third.add(second) + "(.5)");
  System.out.println(zero.multiply(first) + "(0)");
  System.out.println(zero.subtract(second) + "(-1.0)");
  System.out.println(third.divide(second) + "(-.5)");
  System.out.println("Rational Numbers");
  RationalNumber fourth = new RationalNumber(1,2);
  RationalNumber fifth = new RationalNumber(1,-2);
  RationalNumber sixth = new RationalNumber(-3,4);
  RationalNumber seventh = new RationalNumber(-5,-10);
  RationalNumber eighth = new RationalNumber(0,3);
  RationalNumber ninth = new RationalNumber(5,1);
  RationalNumber tenth = new RationalNumber(7,-10);
  System.out.println(fourth + " (1/2)");
  System.out.println(fifth + " (-1/2)");
  System.out.println(sixth + " (-3/4)");
  System.out.println(seventh + " (1/2)");
  System.out.println(eighth + " (0)");
  System.out.println(ninth + " (5)");
  System.out.println(tenth + " (-7/10) \nTesting .equals");
  System.out.println(fourth.equals(seventh) + " (true)");
  System.out.println(fifth.equals(fourth) + " (false)");
  System.out.println(eighth.equals(ninth) + " (false)");
  System.out.println(tenth.equals(sixth) + " (false)");
  System.out.println(ninth.equals(tenth) + " (false)");
  System.out.println(fifth.multiply(seventh).equals(seventh.multiply(fifth)) + " (true)\nTesting reciprocal");
  System.out.println(fourth.reciprocal() + " (2)");
  System.out.println(fifth.reciprocal() + " (-2)");
  System.out.println(sixth.reciprocal() + " (-4/3)");
  System.out.println(seventh.reciprocal() + " (2)");
  System.out.println(eighth.reciprocal() + " (0)");
  System.out.println(ninth.reciprocal() + " (1/5)");
  System.out.println(tenth.reciprocal() + " (-10/7) \nTesting multiply");
  System.out.println(fifth.multiply(seventh) + " (-1/4)");
  System.out.println(sixth.multiply(fifth) + " (3/8)");
  System.out.println(eighth.multiply(sixth) + " (0)");
  System.out.println(tenth.multiply(tenth) + " (49/100)");
  System.out.println(eighth.multiply(ninth) + " (0)");
  System.out.println(ninth.multiply(tenth) + " (-7/2)");
  System.out.println(tenth.multiply(fifth) + " (7/20)\nTesting divide");
  System.out.println(fifth.divide(seventh) + " (-1)");
  System.out.println(sixth.divide(fifth) + " (3/2)");
  System.out.println(eighth.divide(sixth) + " (0)");
  System.out.println(tenth.divide(tenth) + " (1)");
  System.out.println(eighth.divide(ninth) + " (0)");
  System.out.println(ninth.divide(tenth) + " (-50/7)");
  System.out.println(tenth.divide(fifth) + " (7/5)\nTesting add");
  System.out.println(fifth.add(seventh) + " (0)");
  System.out.println(sixth.add(fifth) + " (-5/4)");
  System.out.println(eighth.add(sixth) + " (-3/4)");
  System.out.println(tenth.add(tenth) + " (-7/5)");
  System.out.println(eighth.add(ninth) + " (5)");
  System.out.println(ninth.add(tenth) + " (-43/10)");
  System.out.println(tenth.add(fifth) + " (-6/5)\nTesting subtract");
  System.out.println(fifth.subtract(seventh) + " (-1)");
  System.out.println(sixth.subtract(fifth) + " (-1/4)");
  System.out.println(eighth.subtract(sixth) + " (3/4)");
  System.out.println(tenth.subtract(tenth) + " (0)");
  System.out.println(eighth.subtract(ninth) + " (-5)");
  System.out.println(ninth.subtract(tenth) + " (57/10)");
  System.out.println(tenth.subtract(fifth) + " (-1/5)");

  }
}
